/* automatically generated by rust-bindgen 0.66.1 and subsequently edited by hand */
mod bindings;
pub use bindings::*;

pub type bits = ::std::os::raw::c_ulonglong;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct Con {
    pub type_: Con__bindgen_ty_1,
    pub sym: Sym,
    pub bits: Con__bindgen_ty_2,
    pub flt: ::std::os::raw::c_char,
}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Target {
    pub name: [::std::os::raw::c_char; 16usize],
    pub apple: ::std::os::raw::c_char,
    pub gpr0: ::std::os::raw::c_int,
    pub ngpr: ::std::os::raw::c_int,
    pub fpr0: ::std::os::raw::c_int,
    pub nfpr: ::std::os::raw::c_int,
    pub rglob: bits,
    pub nrglob: ::std::os::raw::c_int,
    pub rsave: *mut ::std::os::raw::c_int,
    pub nrsave: [::std::os::raw::c_int; 2usize],
    pub retregs: ::std::option::Option<
        unsafe extern "C" fn(arg1: Ref, arg2: *mut ::std::os::raw::c_int) -> bits,
    >,
    pub argregs: ::std::option::Option<
        unsafe extern "C" fn(arg1: Ref, arg2: *mut ::std::os::raw::c_int) -> bits,
    >,
    pub memargs: ::std::option::Option<
        unsafe extern "C" fn(arg1: ::std::os::raw::c_int) -> ::std::os::raw::c_int,
    >,
    pub abi0: ::std::option::Option<unsafe extern "C" fn(arg1: *mut Fn)>,
    pub abi1: ::std::option::Option<unsafe extern "C" fn(arg1: *mut Fn)>,
    pub isel: ::std::option::Option<unsafe extern "C" fn(arg1: *mut Fn)>,
    pub emitfn: ::std::option::Option<unsafe extern "C" fn(arg1: *mut Fn, arg2: *mut FILE)>,
    pub emitfin: ::std::option::Option<unsafe extern "C" fn(arg1: *mut FILE)>,
    pub asloc: [::std::os::raw::c_char; 4usize],
    pub assym: [::std::os::raw::c_char; 4usize],
}

extern "C" {
    pub static mut T_amd64_sysv: Target;
}

extern "C" {
    pub static mut T_amd64_apple: Target;
}

extern "C" {
    pub static mut T_arm64: Target;
}

extern "C" {
    pub static mut T_arm64_apple: Target;
}

extern "C" {
    pub static mut T_rv64: Target;
}

extern "C" {
    pub static mut tlist: [*mut Target; 6usize];
}

extern "C" {
    pub static mut outf: *mut FILE;
}

extern "C" {
    pub static mut dbg: ::std::os::raw::c_int;
}

extern "C" {
    pub fn main(
        ac: ::std::os::raw::c_int,
        av: *mut *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
